<h1><a style="color: white" href="http://www.youtube.com/watch?v=NwTsZHGQ6FE">I made this for YOU!!</a></h1>
<p>This site took me over 50 hours to program over the course of the last 4 
weeks.&nbsp; If this site helped save you some bucks, please consider donating a 
dollar back to help support the site.&nbsp; Hosting the site and domain name 
costs real money!</p>
<p>Plus if you donate, you&#39;ll be my best friend forever.&nbsp; You could 
alternatively give me a hi-five next time you see me.</p>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick" />
<input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHPwYJKoZIhvcNAQcEoIIHMDCCBywCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYCe9XWjKef+HXLBaufwxdQSS/1X66UonuIU786qIQxfUVhdF2xRBZ21LPbwIXsx6YSiTrQixxlLqcmwnJ2bOI1XCwV2Y6RTFcZ9xKKek1UsPfhjcRMSaedw6eZ1ssJN//4RkNXav0DPliEHvl2aJOUZhGaYPYbI6D+g06Vas8RihDELMAkGBSsOAwIaBQAwgbwGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIPDuKUcn/5z2AgZhUZrj6L3FTPDixMAk3DeOfGPBkE1sEKNlv+ACTrOB27OveTmxg/afZ8tMXJm/7VpnB725rFQkO7/ZmFo7CjsvPNh4Qmx2uHjLKAzizvBhK/axFG3WMxg4dPm5pcvhlVGHWr2Gsoxs66/rS9Z6iFZgFAXoZpxMGvLwx8+cEZLHTd1byVK/qEjGlNQXeDOgzhlFIIcoEjKBBH6CCA4cwggODMIIC7KADAgECAgEAMA0GCSqGSIb3DQEBBQUAMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTAeFw0wNDAyMTMxMDEzMTVaFw0zNTAyMTMxMDEzMTVaMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAwUdO3fxEzEtcnI7ZKZL412XvZPugoni7i7D7prCe0AtaHTc97CYgm7NsAtJyxNLixmhLV8pyIEaiHXWAh8fPKW+R017+EmXrr9EaquPmsVvTywAAE1PMNOKqo2kl4Gxiz9zZqIajOm1fZGWcGS0f5JQ2kBqNbvbg2/Za+GJ/qwUCAwEAAaOB7jCB6zAdBgNVHQ4EFgQUlp98u8ZvF71ZP1LXChvsENZklGswgbsGA1UdIwSBszCBsIAUlp98u8ZvF71ZP1LXChvsENZklGuhgZSkgZEwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tggEAMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAgV86VpqAWuXvX6Oro4qJ1tYVIT5DgWpE692Ag422H7yRIr/9j/iKG4Thia/Oflx4TdL+IFJBAyPK9v6zZNZtBgPBynXb048hsP16l2vi0k5Q2JKiPDsEfBhGI+HnxLXEaUWAcVfCsQFvd2A1sxRr67ip5y2wwBelUecP3AjJ+YcxggGaMIIBlgIBATCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTExMDExMzIxMTE1NVowIwYJKoZIhvcNAQkEMRYEFKgrfcA1Mdd+xAxIQij0tI9iY+W0MA0GCSqGSIb3DQEBAQUABIGAjsb1hGaR2V0UoeSseNx9UhEC7NhCPx2o133/2PgXToKlcLhAwXnDtKoF8US4YWyEigSr9bg3qw4CMbTOx94QhojFcmpEU7HT4w2iWCBVZ84ukPWreCJh/P9B+zcRRptdcDWCNbusigdxBOUiI8gZmgQHBrU6Cyp2t6or29L7zR4=-----END PKCS7-----
">
<input type="image" src="https://www.paypal.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!" />
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
</form>
<p>Whether or not you donate, thanks for using the Campus Bullet!&nbsp; It was a 
lot of fun to program =)</p>
<p>Dustin</p>